### ISSUE TITLE
Refactor CLI

### ISSUE THREAD

**Issue by shiyuhang0** [tidbcloud/tidbcloud-cli#121]
**Background**

Refactor CLI according to the new open API.

**Roadmap step1**

- [x] TiDB Serverless backup restore open API design
- [x] TiDB Serverless backup restore open API implement
- [x] CLI design
- [x] [Support Serverless CRUD](https://github.com/tidbcloud/tidbcloud-cli/pull/116)
- [x] [Support Serverless branch](https://github.com/tidbcloud/tidbcloud-cli/pull/124)
- [x] [Support Serverless backup/restore](https://github.com/tidbcloud/tidbcloud-cli/pull/127)
- [x] [Move shell/import to serverless and refactor the whole code structure](https://github.com/tidbcloud/tidbcloud-cli/pull/132)
- [ ] ~~[Support billing](https://github.com/tidbcloud/tidbcloud-cli/pull/130)~~
- [x] [Support chat-bot](https://github.com/tidbcloud/tidbcloud-cli/pull/123)
- [ ] Support OAuth

**Roadmap step2 (introduce dedicated)**

- [ ] Support Dedicated cluster
- [ ] Support Dedicated backup/restore
- [ ] Support Dedicated import
